apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: oebs-mainmanager-api
  namespace: team-oebs
  labels:
    app: oebs-mainmanager-api
    team: team-oebs

spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 2

  resources:
    requests:
      cpu: 200m
      memory: 448Mi
    limits:
     # cpu: 4000m
      memory: 512Mi

  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
  envFrom:
    - secret: main-manager

  accessPolicy:
    outbound:
      external:
        - host: nav.mainmanager.no
        - host: a34duvw10783.devillo.no
        - ipv4: 10.53.136.157
          ports:
            - port: 1551


        - ipv4: 10.53.164.110  # dmv31db01.adeo.no
          ports:
            - port: 1521
        - ipv4: 10.53.164.112  # dmv31db02.adeo.no
          ports:
            - port: 1521
        - ipv4: 10.53.164.111  # dmv31db01-vip.adeo.no
          ports:
            - port: 1521
        - ipv4: 10.53.164.113  # dmv31db02-vip.adeo.no
          ports:
            - port: 1521

        - ipv4: 10.53.164.107  # dmv31-scan.adeo.no
          ports:
            - port: 1521
        - ipv4: 10.53.164.108  # dmv31-scan.adeo.no
          ports:
            - port: 1521
        - ipv4: 10.53.164.109  # dmv31-scan.adeo.no
          ports:
            - port: 1521

        - host: dmv31-scan.adeo.no
          ports:
            - port: 1521
  prometheus:
    enabled: true
    path: /actuator/prometheus

  ingresses:
    - "https://oebs-mainmanager.nav.no"
    - "https://oebs-mainmanager.intern.nav.no"