apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: oebs-mainmanager-api-q1
  namespace: team-oebs
  labels:
    app: oebs-mainmanager-api-q1
    team: team-oebs
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1

  resources:
    requests:
      cpu: 10m
      memory: 448Mi
    limits:
      # cpu: 4000m
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
  envFrom:
    - secret: main-manager-q1

  accessPolicy:
    outbound:
      external:
        - host: dmv08db01.adeo.no
          ports:
            - port: 1521
            - port: 1606
        - ipv4: 10.53.161.78
          ports:
            - port: 1521
            - port: 1606
        - host: dmv08db02.adeo.no
          ports:
            - port: 1521
            - port: 1606
        - host: nav-qa.mainmanager.no
        - host: a34duvw10783.devillo.no
        - ipv4: 10.53.136.150
          ports:
            - port: 1609
        - host: dmv08-scan.adeo.no #10.53.161.77
          ports:
            - port: 1521

  prometheus:
    enabled: true
    path: /actuator/prometheus

  ingresses:
    - "https://oebs-mainmanager-api-q1.intern.dev.nav.no"
    - "https://oebs-mainmanager-api-q1.ekstern.dev.nav.no"