apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: oebs-mainmanager-api
  namespace: team-oebs
  labels:
    app: oebs-mainmanager-api
    team: team-oebs

spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 3
    max: 3

  resources:
    requests:
      cpu: 110m
      memory: 448Mi
    limits:
     # cpu: 4000m
      memory: 512Mi

  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
  envFrom:
    - secret: main-manager

  accessPolicy:
    outbound:
      external:
        - host: nav.mainmanager.no
        - host: a34duvw10783.devillo.no
        - ipv4: 10.53.136.157
          ports:
            - port: 1551

  prometheus:
    enabled: true
    path: /actuator/prometheus

  ingresses:
    - "https://oebs-mainmanager.nav.no"
    - "https://oebs-mainmanager.intern.nav.no"