
server:
  port: 8080

no.nav.security.jwt:
   issuer:
     azure:
       accepted_audience: ${AZURE_ACCEPTED_AUDIENCE}
       discovery-url: ${AZURE_DISCOVERY_URL}

# Add these if needed for SSL

spring:
  profiles:
     active: nais
  datasource:

    hikari:
      data-source-properties:
        oracle:
          net:
            ssl_version: 1.2
            ssl_server_dn_match: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

    driver-class-name: oracle.jdbc.OracleDriver
    username: ${APPS_USER}
    password: ${APPS_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
        use__jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: false
    open-in-view: false
  application:
    name: ${APP_NAME}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics

springdoc:
  packagesToScan: no.nav.oebs.api.controller
  override-with-generic-response: false
  remove-broken-reference-definitions: false
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha

logging:
  level:
     org:
       hibernate: ERROR
    #com.zaxxer.hikari: DEBUG
    # root: DEBUG
    # org.springframework.web: debug
    # org.hibernate: error
    # org.springframework: DEBUG
    # no.nav= DEBUG