
server:
  port: 8080

no.nav.security.jwt:
   issuer:
     azure:
       accepted_audience: ${AZURE_ACCEPTED_AUDIENCE}
       discovery-url: ${AZURE_DISCOVERY_URL}
       # proxyurl: ${AZURE_PROXY_URL}

spring:
  profiles:
     active: nais
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${APPS_USER}
    password: ${APPS_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    show-sql: false
    open-in-view: false
  application:
    name: ${APP_NAME}

oebs:
  environment: Oebst1
  version: 0.3.0
  date: 10.09.2024

mainmanager:
  vendors:
    usted: ${MM_VENDORS}
    sted: ${MM_VENDORS_STED}
  url:
    token: ${MM_URL_TOKEN}
  artskonto: ${MM_ART}
  kostnadssted: ${MM_KOSTNADSSTED}
  produkt: ${MM_PRODUKT}
  oppgave: ${MM_OPPGAVE}
  statsregnskapskonto: ${MM_STATSREGNSKAPSKONTO}
  felles: ${MM_FELLES}
  username: ${MM_USER}
  password: ${MM_PASSWORD}
  grant_type: ${MM_GRANT_TYPE}

#debug: true


management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics

springdoc:
  packagesToScan: no.nav.oebs.api.controller
  override-with-generic-response: false
  remove-broken-reference-definitions: false
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha

#logging:
  #level:
    #com.zaxxer.hikari: DEBUG
    # root: DEBUG
    # org.springframework.web: debug
    # org.hibernate: error
    # org.springframework: DEBUG

logging.level:
  org.springframework: INFO
  no.nav: DEBUG