spring.datasource.username=${APPs_USER}
spring.datasource.password=${APPS_PASSWORD}
spring.datasource.url=${DB_URL}
spring.application.name=${APP_NAME}
no.nav.security.jwt.issuer.azure.accepted_audience=${AZURE_ACCEPTED_AUDIENCE}
no.nav.security.jwt.issuer.azure.discoveryurl=${AZURE_DISCOVERY_URL}
no.nav.security.jwt.issuer.azure.proxyurl=${AZURE_PROXY_URL}
oebs.environment=Oebst1
oebs.version=0.3.0
oebs.date=10.09.2024

mainmanager.vendors.sted=${MM_VENDORS_STED}
mainmanager.vendors=${MM_VENDORS}
mainmanager.url.token=${MM_URL_TOKEN} 
mainmanager.artskonto=${MM_ART}
mainmanager.kostnadsstedsgruppe=${MM_KOSTNADSSTED_GRUPPE}
mainmanager.kostnadssted=${MM_KOSTNADSSTED}
mainmanager.produkt=${MM_PRODUKT}
mainmanager.oppgave=${MM_OPPGAVE}
mainmanager.statsregnskapskonto=${MM_STATSREGNSKAPSKONTO}
mainmanager.felles=${MM_FELLES}
mainmanager.proxy.url=${MM_PROXY_URL}
mainmanager.proxy.port=${MM_PROXY_PORT}

mainmanager.username=${MM_USER}
mainmanager.password=${MM_PASSWORD}
mainmanager.grant_type=${MM_GRANT_TYPE}