
CREATE TABLE xxrtv.xxrtv_mainmanager_logg
( kall_logg_id        NUMBER        NOT NULL
    , korrelasjon_id      VARCHAR2(50)  NOT NULL
    , tidspunkt           TIMESTAMP(9)  NOT NULL
    , type                VARCHAR2(10)  NOT NULL
    , kall_retning        VARCHAR2(10)  NOT NULL
    , method              VARCHAR2(10)
    , operation           VARCHAR2(100) NOT NULL
    , status              NUMBER
    , kalltid             NUMBER        NOT NULL
    , request             CLOB
    , response            CLOB
    , logginfo            VARCHAR2(3000)
    , CONSTRAINT xxrtv_mainmanager_pk PRIMARY KEY(kall_logg_id)
)
    PARTITION BY RANGE ("TIDSPUNKT") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("APPS_TS_TX_DATA")
                    (PARTITION "KALL_LOGG_P1"  VALUES LESS THAN (TIMESTAMP' 2023-04-23 00:00:00') SEGMENT CREATION DEFERRED )  ENABLE ROW MOVEMENT ;

--CREATE UNIQUE INDEX "XXRTV"."XXRTV_MAINMANAGER_U1" ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" ("KALL_LOGG_ID" DESC)  TABLESPACE "APPS_TS_TX_IDX" ;
CREATE INDEX "XXRTV_MAINMANAGER_KAL_U1" ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" ("TIDSPUNKT") TABLESPACE "APPS_TS_TX_IDX"  LOCAL;
CREATE INDEX "XXRTV_MAINMANAGER_KAL_U2" ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" ("KALL_RETNING", "TIDSPUNKT") TABLESPACE "APPS_TS_TX_IDX"  local;
CREATE INDEX "XXRTV_MAINMANAGER_KAL_U3" ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" ("OPERATION", "TIDSPUNKT") TABLESPACE "APPS_TS_TX_IDX"  local;
CREATE INDEX "XXRTV_MAINMANAGER_KAL_U4" ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" ("OPERATION", "KALL_LOGG_ID") TABLESPACE "APPS_TS_TX_IDX"  local;

create public synonym xxrtv_mainmanager_logg for xxrtv.xxrtv_mainmanager_logg;

CREATE  SEQUENCE xxrtv_mainmanager_seq
    START WITH 1
    INCREMENT BY 1;

GRANT ALTER ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" TO "APPS";
GRANT DELETE ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" TO "APPS";
GRANT INDEX ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" TO "APPS";
GRANT INSERT ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" TO "APPS";
GRANT SELECT ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" TO "APPS";
GRANT UPDATE ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" TO "APPS";
GRANT REFERENCES ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" TO "APPS";
GRANT READ ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" TO "APPS";
  GRANT ON COMMIT REFRESH ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" TO "APPS";
  GRANT QUERY REWRITE ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" TO "APPS";
  GRANT DEBUG ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" TO "APPS";
  GRANT FLASHBACK ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" TO "APPS";
GRANT SELECT ON "XXRTV"."XXRTV_MAINMANAGER_LOGG" TO "EBS_UTIL";